config/routes.rb
Rails.application.routes.draw do

  resources :contacts

=begin
  get 'dashboard/index'

  get 'dashboard/login'

  get 'dashboard/equipos'

  get 'dashboard/gallerias'

  get 'dashboard/imagenes'

  get 'dashboard/videos'
=end

  resources :discounts

  resources :categories

  resources :brands

  resources :packages

  resources :comments

  resources :videos

  resources :images

  resources :galleries

  resources :equipment

  get 'welcome/index'

  resources :module5s

  resources :module4s

  resources :module3s

  resources :module2s

  resources :module1s

  get 'password_resets/new'

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new , :as => "login"
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :welcome do
    get 'welcome/index' => :new
    post 'welcome/index' => :create
    delete 'welcome/index' => :destroy
    delete 'welcome/logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :welcome

  resources :users

  resources :rols

  resources :password_resets

  controller :users do
    get 'recover_password' => :recover_password
    post 'recover_password' => :recover_password 
    get 'new_recover_password' => :new_recover_password
    post 'new_recover_password' => :new_recover_password 
    get 'cambiar_password' => :cambiar_password
    post 'cambiar_password' => :cambiar_password
    get 'new_cambiar_password' => :new_cambiar_password
    post 'new_cambiar_password' => :new_cambiar_password
  end 

  controller :galleries do
    get ':id/galerias' => :index , :as => 'galeria_index'
    get ':equip/galerias/:id' => :show , :as => 'galeria_show_p'
    get 'Mi_Panel/:equip/galerias/:id' => :show , :as => 'galeria_show'
    get 'Mi_Panel/:equip/galeria_nueva/' => :new , :as => 'galeria_nueva'
    post 'Mi_Panel/:equip/galeria_nueva/' => :new
    get 'Mi_Panel/:equip/galeria/:id/editar' => :edit , :as => 'galeria_edit'
    post 'Mi_Panel/:equip/galeria/:id/editar' => :edit
  end  
  controller :videos do
    get 'Mi_Panel/:equip/:gal/videos' => :index , :as => 'video_index'
    get 'Mi_Panel/:equip/:gal//videos/:id' => :show , :as => 'video_show'
    get 'Mi_Panel/:equip/:gal/video_nuevo' => :new, :as => 'video_nuevo'
    post 'Mi_Panel/:equip/:gal/video_nuevo' => :new
    get 'Mi_Panel/:equip/:gal/:id/editar' => :new , :as => 'video_edit'
    post 'Mi_Panel/:equip/:gal/:id/editar' => :new
  end  
  controller :images do
    get 'Mi_Panel/:equip/:gal/imagenes' => :index, :as => 'imagen_index'
    get 'Mi_Panel/:equip/:gal/imagenes/:id' => :index , :as => 'imagen_show'
    get 'Mi_Panel/:equip/:gal/imagen_nueva' => :new, :as => 'imagen_nueva'
    post 'Mi_Panel/:equip/:gal/imagen_nueva' => :new
    get 'Mi_Panel/:equip/:gal/editar/:id' => :edit, :as => 'imagen_editar'
    post 'Mi_Panel/:equip/:gal/editar/:id' => :edit
    get 'change_image/:image/:equipment/:gallery' => :select_image , :as => 'select_image'
  end

  controller :comments do
    get 'Mi_Panel/:id/comentarios' => :index, :as => 'comentarios_index'
    get 'Mi_Panel/:equip/comentarios/:id' => :show, :as => 'comentarios_show'
    get 'Mi_Panel/:id/comentario_nuevo' => :new, :as => 'comentario_nuevo'
    post 'Mi_Panel/:id/comentartio_nuevo' => :new
    get 'Mi_Panel/:equip/editar/:id' => :edit, :as => 'comentario_editar'
    post 'Mi_Panel/:equip/editar/:id' => :edit
  end   

  controller :equipment do
    get 'Filtro' => :grid 
    post 'Filtro' => :grid    
    get '/equipo/contacto' => :contact
    post '/equipo/contacto' => :contact
    post '/send' => :sender
    get '/previsalizar/:id' => :preview , as: 'preview'
    get 'Mi_Panel/:equip/impulsar' => :master_console, :as => 'master_console'
    post 'Mi_Panel/:equip/impulsar' => :master_console_exe , :as => 'master_console_exe'
    get  'equipos/resultados' => :search , :as => 'search'
    post 'equipos/resultados' => :search
    get 'equipos/listado' => :users_view, :as => 'users_view'
    get 'industrias/:industria' => :industry, :as => 'industry'
    post 'industrias/:industria' => :industry
    get 'fav_new' => :add_favorito, :as => 'new_fav'
    get 'fav_destroy' => :removed_favoritos, :as => 'del_fav'
    get 'reactivar/:equipment' => :reactivate, :as => 'reactivate'
    get 'anuncios' => :temporal, :as => 'anuncios_t'
  end

  controller :dashboard do
    get 'Mi_Panel' => :index, :as => 'dashboard_index' 
    get 'Mi_Panel/Administracion_de_Cuenta' =>:login, :as => 'dashboard_login'
    get 'Mi_Panel/equipos' => :equipos, :as => 'dashboard_equipos'
    get 'Mi_Panel/:equip/galerias' => :gallerias, :as => 'dashboard_gallerias'
    get 'Mi_Panel/:equip/:gal/imagenes' => :imagenes, :as => 'dashboard_imagenes'
    get 'Mi_Panel/:equip/:gal/videos' => :videos, :as => 'dashboard_videos'
    get 'Mi_Panel/Mis_Equipos' => :equip_history, :as => 'dashboard_equip_history'
    get 'Mi_Panel/Reporte_de_Estado' => :report_status, :as => 'dashboard_status_rep'
    get 'Mi_Panel/Mis_Equipos_Favoritos' => :favorites , :as => 'dashboard_favorite'
  end  

  controller :categories do
    get 'category/vista' => :vista
  end
  
  get 'auth/:provider/callback', to: 'sessions#createfb'
  post 'auth/:provider/callback', to: 'sessions#createfb'
  get 'auth/failure', to: redirect('/')
  post 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy'
  post 'signout', to: 'sessions#destroy'

  get 'auth/google_oauth2/callback?error=access_denied', to: redirect('/')
  get 'nosotros', to: 'welcome#nosotros'
  get 'especiales', to: 'welcome#especiales'
  get 'marcas', to: 'welcome#marcas'
  get 'contactanos', to: 'welcome#contactanos'      

  

  root 'welcome#index'

end

app/controllers/dashboard_controller.rb
#!/bin/env ruby
# encoding: utf-8
class DashboardController < ApplicationController
  before_action :charge_all
  skip_before_action :authorize, only: [:login]


  def index
    @user = User.find(session[:user_id])
  end

  def login
    add_breadcrumb "Administrar cuenta"
     @user = User.find(session[:user_id])  
     #puts "---------------------------------"
     #puts @user.inspect
     #puts "---------------------------------"     
  end

  #mis equipos
  
  def equipos
    add_breadcrumb I18n.t("breadcrumbs.equipment"), dashboard_equipos_path()
    @equipment = Equipment.where("user_id = ?" , session[:user_id]).where_activo
    @equipment2 = Equipment.where("user_id = ?" , session[:user_id]).where_inactivo
    @equipment3 = Equipment.where("user_id = ?" , session[:user_id]).where_desactivado
  end

  def gallerias
    add_breadcrumb I18n.t("breadcrumbs.equipment"), dashboard_equipos_path()    
    @equips = Equipment.friendly.find(params[:equip])
    @galleries = Gallery.where("equipment_id = ?", @equips)
    #if params[:gal]
    #  @galleries = Gallery.friendly.find(params[:gal])
    #end  
    #puts "----------Gallery-----------------------"
    #puts @galleries.inspect
    # puts "----------------------------------------"

    # puts "---------------- equipment -----------------"
    # puts @equips.inspect
    # puts "---------------------------------"
      @e_id = @equips.slug
  end

  def imagenes
    @equips = Equipment.friendly.find(params[:equip])
    if params[:gal]
     # puts "----------Gallery-----------------------"
     # puts  params[:gal]
     # puts "----------------------------------------"
      @galleries = Gallery.friendly.find(params[:gal])
      @images = Image.where("gallery_id = ?" , @galleries.id)
    else
      redirect_to root_path  
    end  
  end

  def videos
    @equips = Equipment.friendly.find(params[:equip])
    @galleries = Gallery.friendly.find(params[:gal])
    @videos = Video.where("gallery_id = ?" , @galleries.id)
  end

  def cuenta       
  end 

  def favorites
    @favoritos = Favorite.select("equipment_id").where("user_id = ?" , session[:user_id])
    array = Array.new
    @favoritos.each do |f|
      array.push(f.equipment_id)
    end
    @equipment = Equipment.where(:id => array).where_activo
  end
  ##generadores de pdf
  def contact_rep
    #@contacts = Contact.find_by_sql("select c.* from contactos c, equipment e where e.user_id = ? and e.id == c.equipment_id group by c.equipment_id order by c.name")
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "report", :layout => 'pdf.html.erp'
      end
    end
  end 
=begin  
  def operations_rep
    @operations = Product.all
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "report", :layout => 'pdf.html.haml'
      end
    end
  end 
=end
  ##generadores de pdf
  def equipments_status_rep
    @equips = Equipment.where('user_id = ?', seesion[:user_id])
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "report", :layout => 'pdf.html.erb'
      end
    end
  end

  def equip_history
    @equipment = Equipment.where("user_id = ?", session[:user_id]).order('created_at ASC')
  end  
  
  #def report_status
  #  @equipments = Equipment.search(params[:search]).where_activo
  #end

  def report_status
    #simple = false
    ##aqui van los campos indispensables
    @user_id = session[:user_id]
    ##terminan indispensables
    add_breadcrumb "Reporte de Status", reporte_status_path('tipo' => 1)

    tipo = params[:tipo]    
    @equipments = Equipment.query_rep_stat(params[:equipment]).where('user_id = ?', @user_id).where_activo.order(sort_column + ' ' + sort_direction)
  end


  private
    def charge_all
 
    @equips = Equipment.find_by("user_id = ?" , session[:user_id])
    unless  @equips.blank?
        @equipsWhere = Equipment.where("user_id = ?" , session[:user_id]).where_activo    
    
        #@galleries = Gallery.find_by("equipment_id = ?" , @equips.id)                 
        @galleriesWhere = Gallery.where("equipment_id = ?" , @equips.id)
        unless @galleries.blank?
          @images = Image.where("gallery_id = ?" , @galleries.id)             
          @videos = Video.where("gallery_id = ?" , @galleries.id)    
        end
        @verificado = true
      else
        @verificado = false
      end
      @verificado  
    end  

    

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_menu.html.erb
Menu
<hr>
	<ul>
		<li><%= link_to "Inicio", dashboard_index_path %></li>
		<% if @verificado %>
			<li><%= link_to "Equipos", dashboard_equipos_path %></li>	
			<!--<li><%#= link_to "-Galería", dashboard_gallerias_path(@equips, @galleries) %></li>
			<li><%#= link_to "--Imagenes", dashboard_imagenes_path(@equips, @galleries) %></li>
			<li><%#= link_to "--Videos", dashboard_videos_path(@equips, @galleries) %></li>	 -->
			<li>Descuentos</li>
			<li>Transacciones</li>	
			<li>Comentarios</li>
		<% end %>
		<li><%= link_to "Favoritos", dashboard_favorite_path %></li>
		<li><%= link_to "Administrar cuenta", dashboard_login_path%></li>		
	</ul>
<hr>

app/views/dashboard/equip_history.html.erb
<table>
	<tr>
		<td>Nombre</td>
		<td>Precio</td>
		<td>Tipo de publicacion</td>
		<td>Status</td>
		<td>Fecha de Creacion</td>
		<td>Ultima Actualización</td>
	</tr>
	<tbody>
		<% @equipment.each do |equip| %>
			<tr>
				<td>equip.name.capitalize</td>
				<td>equip.price</td>
				<td>equip.publication_type</td>
				<td>equip.status.capitalize</td>
				<td>equip.created_at</td>
				<td>equip.updated_at</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/dashboard/equipos.html.erb
<h1>Mis Anuncios</h1>

<div class="dashboard_menu">
	<%= render 'menu' %>
</div>

<div class="dashboard_contenido">
	<% @equipment.each do |equipment| %>
	<div class="lista_show_equipment">
	  <% if equipment.image_id %>
	    <% @image = Image.find(equipment.image_id) %>
	    	<% unless @image.image_url.blank? %>
	    		<div class="lista_image"><img src="<%= @image.image_url %>"></div>   
            <% else
            	unless @image.photo.url.blank?%>  
              		<div class="lista_image"><%= image_tag @image.photo.url(:large) %></div>
              	<% end	
            end %>	  
	  <% else %>
	    <div class="lista_image"><img src="/data/dummy.png"></div>
	  <% end %>
	  <div class="datos">
	    <div class="titulo">
	      <%= link_to equipment.name, equipment_path(equipment) %>
	    </div>
	    <div class="descripcion">
	     Marca: <%= equipment.brand.name %> | Modelo: <%= equipment.modelo %> 
	     <br>
	     Año: <%= equipment.year %> | Color: <%= equipment.color %>
	    </div>
	  </div>
	  <div class="precio">
	    Precio <%if equipment.publication_type == 1 %>Venta<% else %>Renta<% end %>: <br/><%= number_to_currency(equipment.precio) %> <%= equipment.currency.name %>
	  </div>
	  <div class="opciones">
	    <%= link_to 'Edit', edit_equipment_path(equipment) %> 
	    <%= link_to 'Galerias', dashboard_gallerias_path(equipment, @galleries) %>
	    <%= link_to 'Impulsar', master_console_path(equipment) %> 
	    <%= link_to 'Desactivar', equipment, method: :delete, data: { confirm: '¿Deseas desactivar la publicación?' } %>
	  </div>    
	</div>
	<% end %>
	<% if @equipment2.size > 0 %>
		<p>equipos pendientes de pago</p>
		<% @equipment2.each do |equipment| %>
		<div class="lista_show_equipment">
		  <% if equipment.image_id %>
		    <% @image = Image.find(equipment.image_id) %>
		  <div class="lista_image"><img src="<%= @image.image_url %>"></div>
		  <% else %>
		    <div class="lista_image"><img src="/data/dummy.png"></div>
		  <% end %>
		  <div class="datos">
		    <div class="titulo">
		      <%= link_to equipment.name, equipment_path(equipment) %>
		    </div>
		    <div class="descripcion">
		     Marca: <%= equipment.brand.name %> | Modelo: <%= equipment.modelo %> 
		     <br>
		     Año: <%= equipment.year %> | Color: <%= equipment.color %>
		    </div>
		  </div>
		  <div class="precio">
		    Precio <%if equipment.publication_type == 1 %>Venta<% else %>Renta<% end %>: <br/><%= number_to_currency(equipment.precio) %> <%= equipment.currency.name %>
		  </div>
		  <div class="opciones">
		    <%= link_to 'Edit', edit_equipment_path(equipment) %> 
		    <%= link_to 'Galerias', dashboard_gallerias_path(equipment, @galleries) %>
		    <%= link_to 'Impulsar', master_console_path(equipment) %> 
		    <%= link_to 'pagar', "#" %>
		  </div>    
		</div>
		<% end %>
	<% end %>
	<% if @equipment3.size > 0 %>
		<p>equipos desactivados</p>
		<% @equipment3.each do |equipment| %>
		<div class="lista_show_equipment">
		  <% if equipment.image_id %>
		    <% @image = Image.find(equipment.image_id) %>
		  <div class="lista_image"><img src="<%= @image.image_url %>"></div>
		  <% else %>
		    <div class="lista_image"><img src="/data/dummy.png"></div>
		  <% end %>
		  <div class="datos">
		    <div class="titulo">
		      <%= link_to equipment.name, equipment_path(equipment) %>
		    </div>
		    <div class="descripcion">
		     Marca: <%= equipment.brand.name %> | Modelo: <%= equipment.modelo %> 
		     <br>
		     Año: <%= equipment.year %> | Color: <%= equipment.color %>
		    </div>
		  </div>
		  <div class="precio">
		    Precio <%if equipment.publication_type == 1 %>Venta<% else %>Renta<% end %>: <br/><%= number_to_currency(equipment.precio) %> <%= equipment.currency.name %>
		  </div>
		  <div class="opciones">
		    <%= link_to 'Edit', edit_equipment_path(equipment) %> 
		    <%= link_to 'Galerias', dashboard_gallerias_path(equipment, @galleries) %>
		    <%= link_to 'Impulsar', master_console_path(equipment) %> 
		    <%= link_to 'activar', reactivate_path(equipment) %>
		  </div>    
		</div>
		<% end %>
	<% end %>
</div>

app/views/dashboard/favorites.html.erb
<h1>Mis Anuncios Favoritos</h1>

<div class="dashboard_menu">
	<%= render 'menu' %>
</div>

<div class="dashboard_contenido">
	<% @equipment.each do |equipment| %>
	<div class="lista_show_equipment">
	  <% if equipment.image_id %>
	    <% @image = Image.find(equipment.image_id) %>
	  <div class="lista_image"><img src="<%= @image.image_url %>"></div>
	  <% else %>
	    <div class="lista_image"><img src="/data/dummy.png"></div>
	  <% end %>
	  <div class="datos">
	    <div class="titulo">
	      <%= link_to equipment.name, equipment_path(equipment) %>
	    </div>
	    <div class="descripcion">
	     Marca: <%= equipment.brand.name %> | Modelo: <%= equipment.modelo %> 
	     <br>
	     Año: <%= equipment.year %> | Color: <%= equipment.color %>
	    </div>
	  </div>
	  <div class="precio">
	    Precio <%if equipment.publication_type == 1 %>Venta<% else %>Renta<% end %>: <br/><%= number_to_currency(equipment.precio) %> <%= equipment.currency.name %>
	  </div>
	  <div class="opciones">
	    <%#= link_to 'Edit', edit_equipment_path(equipment) %> 
	    <%#= link_to 'Galerias', dashboard_gallerias_path(equipment, @galleries) %>
	    <%#= link_to 'Impulsar', master_console_path(equipment) %> 
	    <%#= link_to 'Desactivar', equipment, method: :delete, data: { confirm: '¿Deseas desactivar la publicación?' } %>
	  </div>    
	</div>
	<% end %>	
</div>

app/views/dashboard/gallerias.html.erb
<h1>Mis Galerias</h1>

<div class="dashboard_menu">
	<%= render 'menu' %>
</div>


<div class="dashboard_contenido">
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Equipment</th>
        <th colspan="5">Agregar</th>                      
      </tr>
    </thead>

    <tbody>
      <% @galleries.each do |gallery| %>
        <tr>
          <td><%= gallery.title %></td>
          <td><%= gallery.equipment.name %></td>
          <td><%= gallery.user_id %></td>
          <td><%= link_to 'Mostrar Galeria', galeria_show_path(@equips,gallery) %></td>
          <%# if @permiso %>
          <td> <%= link_to 'Mostrar Imagenes', dashboard_imagenes_path(@equips,gallery.slug) %>  <%#= link_to 'Edit', edit_gallery_path(gallery) %></td>
          <td><%= link_to 'Mostrar Video', dashboard_videos_path(@equips,gallery.slug) %><%#= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
          <%# end %>
          <!--<td> <%#= link_to 'Show', gallery %></td>
          <td><%#= link_to 'Edit', edit_gallery_path(gallery) %></td>-->
          <% unless gallery.title == "principal" %>
              <td><%= link_to 'Borrar Galeria', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% else %>
              <td></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'Nueva Galeria', galeria_nueva_path(@e_id)  %>
</div>

app/views/dashboard/imagenes.html.erb
<h1>Mis Imagenes</h1>

<div class="dashboard_menu">
	<%= render partial: 'menu' %>
</div>

<div class="dashboard_contenido">
	<table>
	  <thead>
	    <tr>
	      <th>Gallery</th>
	      <th>Image url</th>
	      <th>Title</th>
	      <th colspan="4"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @images.each do |image| %>
	      <tr>
	        <td><%= image.gallery_id %></td>
	        <td><%= image.image_url %></td>
	        <td><%= image.title %></td>
	        <td><%= link_to 'Show', image %></td>
	        <td><%= link_to 'Edit', edit_image_path(image) %></td>
	        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>

	<br>

	<%= link_to 'New Image', new_image_path %>
</div>

app/views/dashboard/index.html.erb
<h1>Mi Cuenta</h1>

<div class="dashboard_menu">
	<%= render 'menu' %>
</div>

app/views/dashboard/login.html.erb
<h1>Dashboard#login</h1>
<p id="notice"><%= notice %></p>
<div class="dashboard_menu">
	<%= render 'menu' %>
</div>
<div class="dashboard_contenido">
<!--

	<%#= render partial: 'users/form', locals: {user: @user} %>

-->
	<%= form_for(@user) do |f| %>
	  <% if @user.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

	      <ul>
	      <% @user.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %> 

	  <div class="field">
	    <%= label_tag @user.username %><br>
	    <%#= f.text_field :username, :disabled => true %>
	  </div>


	  <div class="field">
	    <%= f.label :password %><br>
	    <%= f.password_field :password %>
	  </div>
	  <div>
	    <%= f.label :password_confirmation %><br>
	    <%= f.password_field :password_confirmation %>
	  </div>

	  <div class="field">
	    <%= f.label :name %><br>
	    <%= f.text_field :name %>
	  </div>
	  <div class="field">
	    <%= f.label :lastname %><br>
	    <%= f.text_field :lastname %>
	  </div>
	  <div class="field">
	    <%= f.label :email %><br>
	    <%= f.email_field :email ,:disabled => true %>
	  </div>

	 
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	<% end %>
</div>

app/views/dashboard/report_status.html.erb
<div class="filtros">
    <%= form_tag dashboard_status_rep_path(), :method => 'get' do %>
    <%#= text_field_tag :search, params[:search] %>
    <%= select("equipment", "name", Equipment.all.collect {|p| [ p.name, p.name ] }.uniq, {include_blank: 'Nombre'}) %>
    <br>
    <%= select("equipment", "status", Equipment.all.collect {|p| [ p.color, p.color ] }.uniq, {include_blank: 'Status'}) %>
    <br>
    <%= select("equipment", "desde", Equipment.all.collect {|p| [ p.precio, number_to_currency(p.precio) ] }.uniq, {include_blank: 'Desde'}) %>
    <br>
    <%= select("equipment", "hasta", Equipment.all.collect {|p| [ p.precio, number_to_currency(p.precio) ] }.uniq, {include_blank: 'Hasta'}) %>
    <br>
    

    <%#= select("equipment", "category_id", Category.all.collect {|p| [ p.title, p.id ] }.uniq, {include_blank: 'Categoria'}) %>
    <br>
    <%= hidden_field_tag :category , @categoria.title %>
    <%= submit_tag "Filtrar", :name => nil %>
    <% end %>
    </div>

<table id ="equipments" class ="pretty" >
    <thead>
      <tr>
        <td align="center"> <%= sortable "Nombre" %></td>
        <td align="center"> <%= sortable "Status" %></td>
        <td align="center"> <%= sortable "Ultimo movimiento" %></td>
      </tr>
    </thead>
    

    <tbody> 
    <% unless @equipments.nil? %>   
        <% @equipments.each do |equipment| %>
          <tr>
            <td align="center"><%= equipment.name %></td>
            <% 
            status = case equipment.status
            when 0
              "inactivo"
            when 1
              "pendiente de pago"  
            when 2
              "activo"
            when 3
              "desactivado"  
            else
              "indefinido"
            end
             %>
            <td align="center"><%= status %></td>
            <td align="center"><%= equipment.updated_at %></td>
          </tr>
        <% end %>
    <% else %>
      <tr> <td> No hay resultados a su busqueda</td> </tr>      
    <% end %>    

      </tbody>
    </table>

app/views/dashboard/videos.html.erb
<h1>Dashboard#videos</h1>

<div class="dashboard_menu">
	<%= render 'menu' %>
</div>

<div class="dashboard_contenido">
	<table>
	  <thead>
	    <tr>
	      <th>Gallery</th>
	      <th>Video url</th>
	      <th>Title</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @videos.each do |video| %>
	      <tr>
	        <td><%= video.gallery_id %></td>
	        <td><%= video.video_url %></td>
	        <td><%= video.title %></td>
	        <td><%= link_to 'Show', video %></td>
	        <td><%= link_to 'Edit', edit_video_path(video) %></td>
	        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>

	<br>

	<%= link_to 'New Video', new_video_path %>
</div>