config/routes.rb
Rails.application.routes.draw do

  resources :contacts

=begin
  get 'dashboard/index'

  get 'dashboard/login'

  get 'dashboard/equipos'

  get 'dashboard/gallerias'

  get 'dashboard/imagenes'

  get 'dashboard/videos'
=end

  resources :discounts

  resources :categories

  resources :brands

  resources :packages

  resources :comments

  resources :videos

  resources :images

  resources :galleries

  resources :equipment

  get 'welcome/index'

  resources :module5s

  resources :module4s

  resources :module3s

  resources :module2s

  resources :module1s

  get 'password_resets/new'

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new , :as => "login"
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :welcome do
    get 'welcome/index' => :new
    post 'welcome/index' => :create
    delete 'welcome/index' => :destroy
    delete 'welcome/logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :welcome

  resources :users

  resources :rols

  resources :password_resets

  controller :users do
    get 'recover_password' => :recover_password
    post 'recover_password' => :recover_password 
    get 'new_recover_password' => :new_recover_password
    post 'new_recover_password' => :new_recover_password 
    get 'cambiar_password' => :cambiar_password
    post 'cambiar_password' => :cambiar_password
    get 'new_cambiar_password' => :new_cambiar_password
    post 'new_cambiar_password' => :new_cambiar_password
  end 

  controller :galleries do
    get ':id/galerias' => :index , :as => 'galeria_index'
    get ':equip/galerias/:id' => :show , :as => 'galeria_show_p'
    get 'Mi_Panel/:equip/galerias/:id' => :show , :as => 'galeria_show'
    get 'Mi_Panel/:equip/galeria_nueva/' => :new , :as => 'galeria_nueva'
    post 'Mi_Panel/:equip/galeria_nueva/' => :new
    get 'Mi_Panel/:equip/galeria/:id/editar' => :edit , :as => 'galeria_edit'
    post 'Mi_Panel/:equip/galeria/:id/editar' => :edit
  end  
  controller :videos do
    get 'Mi_Panel/:equip/:gal/videos' => :index , :as => 'video_index'
    get 'Mi_Panel/:equip/:gal//videos/:id' => :show , :as => 'video_show'
    get 'Mi_Panel/:equip/:gal/video_nuevo' => :new, :as => 'video_nuevo'
    post 'Mi_Panel/:equip/:gal/video_nuevo' => :new
    get 'Mi_Panel/:equip/:gal/:id/editar' => :new , :as => 'video_edit'
    post 'Mi_Panel/:equip/:gal/:id/editar' => :new
  end  
  controller :images do
    get 'Mi_Panel/:equip/:gal/imagenes' => :index, :as => 'imagen_index'
    get 'Mi_Panel/:equip/:gal/imagenes/:id' => :index , :as => 'imagen_show'
    get 'Mi_Panel/:equip/:gal/imagen_nueva' => :new, :as => 'imagen_nueva'
    post 'Mi_Panel/:equip/:gal/imagen_nueva' => :new
    get 'Mi_Panel/:equip/:gal/editar/:id' => :edit, :as => 'imagen_editar'
    post 'Mi_Panel/:equip/:gal/editar/:id' => :edit
    get 'change_image/:image/:equipment/:gallery' => :select_image , :as => 'select_image'
  end

  controller :comments do
    get 'Mi_Panel/:id/comentarios' => :index, :as => 'comentarios_index'
    get 'Mi_Panel/:equip/comentarios/:id' => :show, :as => 'comentarios_show'
    get 'Mi_Panel/:id/comentario_nuevo' => :new, :as => 'comentario_nuevo'
    post 'Mi_Panel/:id/comentartio_nuevo' => :new
    get 'Mi_Panel/:equip/editar/:id' => :edit, :as => 'comentario_editar'
    post 'Mi_Panel/:equip/editar/:id' => :edit
  end   

  controller :equipment do
    get 'Filtro' => :grid 
    post 'Filtro' => :grid    
    get '/equipo/contacto' => :contact
    post '/equipo/contacto' => :contact
    post '/send' => :sender
    get '/previsalizar/:id' => :preview , as: 'preview'
    get 'Mi_Panel/:equip/impulsar' => :master_console, :as => 'master_console'
    post 'Mi_Panel/:equip/impulsar' => :master_console_exe , :as => 'master_console_exe'
    get  'equipos/resultados' => :search , :as => 'search'
    post 'equipos/resultados' => :search
    get 'equipos/listado' => :users_view, :as => 'users_view'
    get 'industrias/:industria' => :industry, :as => 'industry'
    post 'industrias/:industria' => :industry
    get 'fav_new' => :add_favorito, :as => 'new_fav'
    get 'fav_destroy' => :removed_favoritos, :as => 'del_fav'
    get 'reactivar/:equipment' => :reactivate, :as => 'reactivate'
    get 'anuncios' => :temporal, :as => 'anuncios_t'
  end

  controller :dashboard do
    get 'Mi_Panel' => :index, :as => 'dashboard_index' 
    get 'Mi_Panel/Administracion_de_Cuenta' =>:login, :as => 'dashboard_login'
    get 'Mi_Panel/equipos' => :equipos, :as => 'dashboard_equipos'
    get 'Mi_Panel/:equip/galerias' => :gallerias, :as => 'dashboard_gallerias'
    get 'Mi_Panel/:equip/:gal/imagenes' => :imagenes, :as => 'dashboard_imagenes'
    get 'Mi_Panel/:equip/:gal/videos' => :videos, :as => 'dashboard_videos'
    get 'Mi_Panel/Mis_Equipos' => :equip_history, :as => 'dashboard_equip_history'
    get 'Mi_Panel/Reporte_de_Estado' => :report_status, :as => 'dashboard_status_rep'
    get 'Mi_Panel/Mis_Equipos_Favoritos' => :favorites , :as => 'dashboard_favorite'
  end  

  controller :categories do
    get 'category/vista' => :vista
  end
  
  get 'auth/:provider/callback', to: 'sessions#createfb'
  post 'auth/:provider/callback', to: 'sessions#createfb'
  get 'auth/failure', to: redirect('/')
  post 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy'
  post 'signout', to: 'sessions#destroy'

  get 'auth/google_oauth2/callback?error=access_denied', to: redirect('/')
  get 'nosotros', to: 'welcome#nosotros'
  get 'especiales', to: 'welcome#especiales'
  get 'marcas', to: 'welcome#marcas'
  get 'contactanos', to: 'welcome#contactanos'      

  

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username,  uniqueness: true
  belongs_to :rol 
  after_destroy :ensure_an_admin_remains
  validates :password, presence: true, length: { in: 6..20 }, :on => :create
  validates :email, 
             presence: true, 
             uniqueness: true
  validates_format_of :email, 
    :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, 
    :message => ' - The email provided does not have a valid format.'
  validates :name, :lastname, presence: true
  has_many :comments

  def send_password_reset
	  generate_token(:password_reset_token)
	  self.password_reset_sent_at = Time.zone.now
	  save!
	  Mailer.password_reset(self).deliver
  end

  def self.from_omniauth(auth)

    @aux = User.find_by(email: auth.info.email)

    if @aux.blank?
      where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|

          user.provider = auth.provider
          user.uid = auth.uid
          user.name = auth.info.first_name
        if :provider == "facebook"  
          user.password = "FBzRGEbIp-"
          user.username = auth.info.name + "_fb"
        elsif :provider == "google_oauth2"
          user.password = "GLOTzRGEbIp-"
          user.username = auth.info.name + "_gl"
        else
          user.password = "OTzRGEbIp-" 
          user.username = auth.info.name + "_ot"   
        end  
          user.email = auth.info.email
          user.lastname = auth.info.last_name
          @rol = Rol.find_by(rol_name: 'usuario')
          user.rol_id = @rol.id
          user.oauth_token = auth.credentials.token
          user.oauth_expires_at = Time.at(auth.credentials.expires_at)
          
          begin
            #some logic
             user.save 
          rescue ActiveRecord::RecordNotSaved => e
            redirect_to root_url, notice: 'su correo ya esta registrado, use uno diferente' 
          end
                     
      end
    else
      user = @aux  
    end
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  private
    def ensure_an_admin_remains
		  if User.count.zero?
        raise "Can't delete last user"
		  end
    end
    
end

app/controllers/users_controller.rb
#!/bin/env ruby
# encoding: utf-8
class UsersController < ApplicationController
  before_action :autorizar
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:recover_password, :new_recover_password]
  skip_before_action :autorizar, only: [:cambiar_password, :new_cambiar_password]
  skip_before_action :autorizar, only: [:new,:create, :update]
  skip_before_action :authorize, only: [:new,:create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new('rol_id' => 2)
  end

  # GET /users/1/edit
  def edit
  end

  def new_recover_password
  end

  def new_cambiar_password
    @user = User.find_by(id: session[:user_id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        Mailer.create_user(@user).deliver
        format.html { login2(@user.email,@user.password)
         #redirect_to @user, notice: "El usuario #{@user.username} fue creado exitosamente." 
       }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if session[:user_id] == @user.id or session[:uname] == "admin@admin.com"
      
      respond_to do |format|
        if @user.update(user_params)
        
          format.html { redirect_to dashboard_login_path, notice: "El usuario #{@user.username} fue actualizado exitosamente." }
          format.json { render :show, status: :ok, location: @user }
        else
         
          format.html { redirect_to dashboard_login_path, notice: "El usuario #{@user.username} no pudo ser actualizado." }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path , notice: " no esta autorizado para hacer esa accion"
    end  
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    begin
      @user.destroy
      Mailer.destroy_user(@user).deliver
      flash[:notice] = "User #{@user.username} deleted"
    rescue StandardError => e
      flash[:notice] = e.message
    end
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end


  def reset_password
    @user = User.where(["username= ? and email= ?",params[:username],params[:email]])
    if @user.empty?
      redirect_to root_path
    else
    puts params  
    @user.update(user_params) 
    Mailer.reset_password(@user,params[:email]).deliver 
    end 
  end
  
  def cambiar_password
    @user = User.find(params[:id]) 
    Mailer.cambiar_password(@user).deliver  

  end 

  def recover_password
    @user = User.where(["username= ? and email= ?",params[:username],params[:email]])
    if @user.empty?
      redirect_to root_path
    else
      #puts @user.inspect
      Mailer.recover_password(@user,params[:email]).deliver 
      redirect_to users_url
    end   
  end
   

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def autorizar
        unless session[:mod0] == true
          redirect_to root_path , notice: " no esta autorizado para hacer esa accion"
        end
    end

    def login2(email, password) 
      user = User.find_by(username: email)
      if user and user.authenticate(password)
        session[:user_id] = user.id
        session[:uname] = user.username
        session[:rol_id] = user.rol_id
      #   puts "---------------------holaaaaaaaaaaa222222222222-------------------"
        #variables de rol
        rol =Rol.find_by(id: user.rol_id)
        session[:mod0] =rol.admin
        session[:mod1] =rol.module_1
        session[:mod2] =rol.module_2
        session[:mod3] =rol.module_3
        session[:mod4] =rol.module_4
        session[:mod5] =rol.module_5
        #termina variables de rol
        unless session[:lasurl].blank?
          aux = session[:lasurl]
          session[:lasurl] = ""
          redirect_to aux
        else
          redirect_to root_path
        end    
      else
        redirect_to root_path, alert: "Invalid user/password combination"
      end
    end
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      unless params[:user][:email].blank?
        if params[:user][:username].blank?
          params[:user][:username] = params[:user][:email]  
        end
      end  


      
      params[:user][:rol_id] = 2
      params.require(:user).permit(:username, :password, :password_confirmation, :name, :lastname, :email, :login_date, :password_date, :rol_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>


  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <!-- <div class="field">
    <%#= f.label :login_date %><br>
    <%#= f.datetime_local_field :login_date %>
  </div> 
  <div class="field">
    <%#= f.label :password_date %><br>
    <%#= f.datetime_local_field :password_date %>
  </div>
  

  <div class="field">
    <%#= f.label :password_date %><br>
    <%#= f.datetime_local_field :password_date %>
  </div> -->
  <div class="field">
    <%#= f.label :rol_id %><br>
    <%#= f.number_field :rol_id %>
    <%#= f.hidden_field :rol_id %>
    <br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_form_cambiar_pass.html.erb
<%= form_for(@user) do |f| %>

	<div class="field">
    	<%= f.label :username %><br>
    	<%= f.text_field :username, :disabled => true %>
  	</div>

	<div class="field">
    	<%= f.label :password %><br>
    	<%= f.password_field :password %>
	</div>

	<div>
    	<%= f.label :password_confirmation %><br>
    	<%= f.password_field :password_confirmation %>
 	</div>

 	<div class="actions">
    <%= f.submit %>
  	</div>

 <% end %>  

app/views/users/_form_recuperar_pass.html.erb
<p> Para recuperar tu password, proporciona tu nombre de usuario y/o correo electr&oacute;nico </p>

<%= form_tag recover_password_path, :method => 'post' do %>
     
  <div class="field">
    <%= label_tag :username, "Nombre de usuario" %><br>
    <%= text_field_tag :username %>
  </div>
  <div class="field">
    <%= label_tag :email, "Email"  %><br>
    <%= email_field_tag :email %>
  </div>

    <div class="actions">
      <%= submit_tag(value="Recuperar Password") %>
  	</div>

<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Login date</th>
      <th>Password date</th>
      <th>Rol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= user.login_date %></td>
        <td><%= user.password_date %></td>
        <td><%= user.rol_id %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="formulario_gris">
  <div class="centrado">

    <h1>Creación de cuenta</h1>

    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %> 

      <div class="field">
        <%#= f.label :username %><br>
        <%= f.hidden_field :username%>
      </div>


      <div class="field">
        <%= f.label :password %><br>
        <%= f.password_field :password, required: true %>
      </div>
      <div>
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation, required: true %>
      </div>

      <div class="field">
        <%= f.label :name, "NOMBRE" %><br>
        <%= f.text_field :name, required: true %>
      </div>
      <div class="field">
        <%= f.label :lastname, "APELLIDO" %><br>
        <%= f.text_field :lastname, required: true %>
      </div>
      <div class="field">
        <%= f.label :email,"CORREO ELECTRÓNICO" %><br>
        <%= f.email_field :email, required: true, pattern: "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+([\.][a-zA-Z0-9-]{2,3}){1,2}$", title: "Ingrese un formato válido Micorreo@tupagina.com" %>
      </div>
      <!-- <div class="field">
        <%#= f.label :login_date %><br>
        <%#= f.datetime_local_field :login_date %>
      </div> 
      <div class="field">
        <%#= f.label :password_date %><br>
        <%#= f.datetime_local_field :password_date %>
      </div>
      

      <div class="field">
        <%#= f.label :password_date %><br>
        <%#= f.datetime_local_field :password_date %>
      </div> -->
      <div class="field">
        <%#= f.label :rol_id %>
        <%#= f.number_field :rol_id %>
        <%= f.hidden_field :rol_id %>
      </div>
      <div class="actions">
        <%= f.submit "Crear" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new_cambiar_password.html.erb
<h1>Cambiar Password</h1>

<%= render 'form_cambiar_pass' %>

app/views/users/new_recover_password.html.erb
<h1>Recuperar Password</h1>

<%= render 'form_recuperar_pass' %>

app/views/users/prueba.html.erb
<h1>Login</h1>
<%= @user.username %>
<%#= render 'form_login' %>
<hr />
<%= render 'form_recuperar_pass' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<!-- <p>
  <strong>Login date:</strong>
  <%= @user.login_date %>
</p>

<p>
  <strong>Password date:</strong>
  <%= @user.password_date %>
</p> -->

<p>
  <strong>Rol:</strong>
  <%= @user.rol_id %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>