config/routes.rb
Rails.application.routes.draw do

  resources :contacts

=begin
  get 'dashboard/index'

  get 'dashboard/login'

  get 'dashboard/equipos'

  get 'dashboard/gallerias'

  get 'dashboard/imagenes'

  get 'dashboard/videos'
=end

  resources :discounts

  resources :categories

  resources :brands

  resources :packages

  resources :comments

  resources :videos

  resources :images

  resources :galleries

  resources :equipment

  get 'welcome/index'

  resources :module5s

  resources :module4s

  resources :module3s

  resources :module2s

  resources :module1s

  get 'password_resets/new'

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new , :as => "login"
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :welcome do
    get 'welcome/index' => :new
    post 'welcome/index' => :create
    delete 'welcome/index' => :destroy
    delete 'welcome/logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :welcome

  resources :users

  resources :rols

  resources :password_resets

  controller :users do
    get 'recover_password' => :recover_password
    post 'recover_password' => :recover_password 
    get 'new_recover_password' => :new_recover_password
    post 'new_recover_password' => :new_recover_password 
    get 'cambiar_password' => :cambiar_password
    post 'cambiar_password' => :cambiar_password
    get 'new_cambiar_password' => :new_cambiar_password
    post 'new_cambiar_password' => :new_cambiar_password
  end 

  controller :galleries do
    get ':id/galerias' => :index , :as => 'galeria_index'
    get ':equip/galerias/:id' => :show , :as => 'galeria_show_p'
    get 'Mi_Panel/:equip/galerias/:id' => :show , :as => 'galeria_show'
    get 'Mi_Panel/:equip/galeria_nueva/' => :new , :as => 'galeria_nueva'
    post 'Mi_Panel/:equip/galeria_nueva/' => :new
    get 'Mi_Panel/:equip/galeria/:id/editar' => :edit , :as => 'galeria_edit'
    post 'Mi_Panel/:equip/galeria/:id/editar' => :edit
  end  
  controller :videos do
    get 'Mi_Panel/:equip/:gal/videos' => :index , :as => 'video_index'
    get 'Mi_Panel/:equip/:gal//videos/:id' => :show , :as => 'video_show'
    get 'Mi_Panel/:equip/:gal/video_nuevo' => :new, :as => 'video_nuevo'
    post 'Mi_Panel/:equip/:gal/video_nuevo' => :new
    get 'Mi_Panel/:equip/:gal/:id/editar' => :new , :as => 'video_edit'
    post 'Mi_Panel/:equip/:gal/:id/editar' => :new
  end  
  controller :images do
    get 'Mi_Panel/:equip/:gal/imagenes' => :index, :as => 'imagen_index'
    get 'Mi_Panel/:equip/:gal/imagenes/:id' => :index , :as => 'imagen_show'
    get 'Mi_Panel/:equip/:gal/imagen_nueva' => :new, :as => 'imagen_nueva'
    post 'Mi_Panel/:equip/:gal/imagen_nueva' => :new
    get 'Mi_Panel/:equip/:gal/editar/:id' => :edit, :as => 'imagen_editar'
    post 'Mi_Panel/:equip/:gal/editar/:id' => :edit
    get 'change_image/:image/:equipment/:gallery' => :select_image , :as => 'select_image'
  end

  controller :comments do
    get 'Mi_Panel/:id/comentarios' => :index, :as => 'comentarios_index'
    get 'Mi_Panel/:equip/comentarios/:id' => :show, :as => 'comentarios_show'
    get 'Mi_Panel/:id/comentario_nuevo' => :new, :as => 'comentario_nuevo'
    post 'Mi_Panel/:id/comentartio_nuevo' => :new
    get 'Mi_Panel/:equip/editar/:id' => :edit, :as => 'comentario_editar'
    post 'Mi_Panel/:equip/editar/:id' => :edit
  end   

  controller :equipment do
    get 'Filtro' => :grid 
    post 'Filtro' => :grid    
    get '/equipo/contacto' => :contact
    post '/equipo/contacto' => :contact
    post '/send' => :sender
    get '/previsalizar/:id' => :preview , as: 'preview'
    get 'Mi_Panel/:equip/impulsar' => :master_console, :as => 'master_console'
    post 'Mi_Panel/:equip/impulsar' => :master_console_exe , :as => 'master_console_exe'
    get  'equipos/resultados' => :search , :as => 'search'
    post 'equipos/resultados' => :search
    get 'equipos/listado' => :users_view, :as => 'users_view'
    get 'industrias/:industria' => :industry, :as => 'industry'
    post 'industrias/:industria' => :industry
    get 'fav_new' => :add_favorito, :as => 'new_fav'
    get 'fav_destroy' => :removed_favoritos, :as => 'del_fav'
    get 'reactivar/:equipment' => :reactivate, :as => 'reactivate'
    get 'anuncios' => :temporal, :as => 'anuncios_t'
  end

  controller :dashboard do
    get 'Mi_Panel' => :index, :as => 'dashboard_index' 
    get 'Mi_Panel/Administracion_de_Cuenta' =>:login, :as => 'dashboard_login'
    get 'Mi_Panel/equipos' => :equipos, :as => 'dashboard_equipos'
    get 'Mi_Panel/:equip/galerias' => :gallerias, :as => 'dashboard_gallerias'
    get 'Mi_Panel/:equip/:gal/imagenes' => :imagenes, :as => 'dashboard_imagenes'
    get 'Mi_Panel/:equip/:gal/videos' => :videos, :as => 'dashboard_videos'
    get 'Mi_Panel/Mis_Equipos' => :equip_history, :as => 'dashboard_equip_history'
    get 'Mi_Panel/Reporte_de_Estado' => :report_status, :as => 'dashboard_status_rep'
    get 'Mi_Panel/Mis_Equipos_Favoritos' => :favorites , :as => 'dashboard_favorite'
  end  

  controller :categories do
    get 'category/vista' => :vista
  end
  
  get 'auth/:provider/callback', to: 'sessions#createfb'
  post 'auth/:provider/callback', to: 'sessions#createfb'
  get 'auth/failure', to: redirect('/')
  post 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy'
  post 'signout', to: 'sessions#destroy'

  get 'auth/google_oauth2/callback?error=access_denied', to: redirect('/')
  get 'nosotros', to: 'welcome#nosotros'
  get 'especiales', to: 'welcome#especiales'
  get 'marcas', to: 'welcome#marcas'
  get 'contactanos', to: 'welcome#contactanos'      

  

  root 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	######################################
	extend FriendlyId
	friendly_id :title, :use => :slugged
	######################################
	validates :title, presence: true, uniqueness: true
	#validates_format_of :title, :with => /^([^\/]*)$/i

	has_many :subcategories
end

app/controllers/categories_controller.rb
#!/bin/env ruby
# encoding: utf-8
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:vista]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  def vista
    @category = Category.all
    @equipment = Equipment.where_activo
  end  
  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :father_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :father_id %><br>
    <%= f.number_field :father_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Father</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.father_id %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Father:</strong>
  <%= @category.father_id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categories/vista.html.erb
<% @category.each do |categoria| %>
		<div class="vista_categoria">
			<div class="vista_categoria_titulo">
				<h6>
					<% @contcat = Equipment.where('category_id = ?', categoria.id).where_activo.count %>
					<%= link_to categoria.title+' ('+@contcat.to_s+')', Filtro_path('categoria' => categoria.title, 'tipo' => 1), method: :post %>
				</h6>
			</div>
			<div class="vista_categoria_productos">
				<% @equipment.each do |equipment| %>
				<% if equipment.category_id.to_s == categoria.id.to_s %>
					<div class="equipos">
						<div class="imagenes">
							<% if equipment.image_id  %>
								<% @images = Image.find(equipment.image_id) %>
								<% if @images.image_url %>
									<div class="imagen">
										<%= link_to image_tag(@images.image_url ), equipment_path(equipment) %>
									</div>
								<%else %> <%= link_to image_tag("/data/dummy.png"), equipment_path(equipment) %>
									<div class="imagen">
										<%= link_to image_tag("/data/dummy.png"), equipment_path(equipment) %>
									</div>  
								<% end %> 
							<% else %>
								<div class="imagen">
									<%= link_to image_tag("/data/dummy.png"), equipment_path(equipment) %>
								</div>  
							<% end %> 
						</div>
						<div class="datos">
							<%= link_to equipment.name, equipment_path(equipment) %><br />
							<%= number_to_currency(equipment.precio) %> <%= equipment.currency.name %>
						</div>
					</div>
				<% end %>
				<% end %>
			</div>	
		</div>
<% end %>   