config/routes.rb
Rails.application.routes.draw do

  resources :contacts

=begin
  get 'dashboard/index'

  get 'dashboard/login'

  get 'dashboard/equipos'

  get 'dashboard/gallerias'

  get 'dashboard/imagenes'

  get 'dashboard/videos'
=end

  resources :discounts

  resources :categories

  resources :brands

  resources :packages

  resources :comments

  resources :videos

  resources :images

  resources :galleries

  resources :equipment

  get 'welcome/index'

  resources :module5s

  resources :module4s

  resources :module3s

  resources :module2s

  resources :module1s

  get 'password_resets/new'

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new , :as => "login"
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :welcome do
    get 'welcome/index' => :new
    post 'welcome/index' => :create
    delete 'welcome/index' => :destroy
    delete 'welcome/logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :welcome

  resources :users

  resources :rols

  resources :password_resets

  controller :users do
    get 'recover_password' => :recover_password
    post 'recover_password' => :recover_password 
    get 'new_recover_password' => :new_recover_password
    post 'new_recover_password' => :new_recover_password 
    get 'cambiar_password' => :cambiar_password
    post 'cambiar_password' => :cambiar_password
    get 'new_cambiar_password' => :new_cambiar_password
    post 'new_cambiar_password' => :new_cambiar_password
  end 

  controller :galleries do
    get ':id/galerias' => :index , :as => 'galeria_index'
    get ':equip/galerias/:id' => :show , :as => 'galeria_show_p'
    get 'Mi_Panel/:equip/galerias/:id' => :show , :as => 'galeria_show'
    get 'Mi_Panel/:equip/galeria_nueva/' => :new , :as => 'galeria_nueva'
    post 'Mi_Panel/:equip/galeria_nueva/' => :new
    get 'Mi_Panel/:equip/galeria/:id/editar' => :edit , :as => 'galeria_edit'
    post 'Mi_Panel/:equip/galeria/:id/editar' => :edit
  end  
  controller :videos do
    get 'Mi_Panel/:equip/:gal/videos' => :index , :as => 'video_index'
    get 'Mi_Panel/:equip/:gal//videos/:id' => :show , :as => 'video_show'
    get 'Mi_Panel/:equip/:gal/video_nuevo' => :new, :as => 'video_nuevo'
    post 'Mi_Panel/:equip/:gal/video_nuevo' => :new
    get 'Mi_Panel/:equip/:gal/:id/editar' => :new , :as => 'video_edit'
    post 'Mi_Panel/:equip/:gal/:id/editar' => :new
  end  
  controller :images do
    get 'Mi_Panel/:equip/:gal/imagenes' => :index, :as => 'imagen_index'
    get 'Mi_Panel/:equip/:gal/imagenes/:id' => :index , :as => 'imagen_show'
    get 'Mi_Panel/:equip/:gal/imagen_nueva' => :new, :as => 'imagen_nueva'
    post 'Mi_Panel/:equip/:gal/imagen_nueva' => :new
    get 'Mi_Panel/:equip/:gal/editar/:id' => :edit, :as => 'imagen_editar'
    post 'Mi_Panel/:equip/:gal/editar/:id' => :edit
    get 'change_image/:image/:equipment/:gallery' => :select_image , :as => 'select_image'
  end

  controller :comments do
    get 'Mi_Panel/:id/comentarios' => :index, :as => 'comentarios_index'
    get 'Mi_Panel/:equip/comentarios/:id' => :show, :as => 'comentarios_show'
    get 'Mi_Panel/:id/comentario_nuevo' => :new, :as => 'comentario_nuevo'
    post 'Mi_Panel/:id/comentartio_nuevo' => :new
    get 'Mi_Panel/:equip/editar/:id' => :edit, :as => 'comentario_editar'
    post 'Mi_Panel/:equip/editar/:id' => :edit
  end   

  controller :equipment do
    get 'Filtro' => :grid 
    post 'Filtro' => :grid    
    get '/equipo/contacto' => :contact
    post '/equipo/contacto' => :contact
    post '/send' => :sender
    get '/previsalizar/:id' => :preview , as: 'preview'
    get 'Mi_Panel/:equip/impulsar' => :master_console, :as => 'master_console'
    post 'Mi_Panel/:equip/impulsar' => :master_console_exe , :as => 'master_console_exe'
    get  'equipos/resultados' => :search , :as => 'search'
    post 'equipos/resultados' => :search
    get 'equipos/listado' => :users_view, :as => 'users_view'
    get 'industrias/:industria' => :industry, :as => 'industry'
    post 'industrias/:industria' => :industry
    get 'fav_new' => :add_favorito, :as => 'new_fav'
    get 'fav_destroy' => :removed_favoritos, :as => 'del_fav'
    get 'reactivar/:equipment' => :reactivate, :as => 'reactivate'
    get 'anuncios' => :temporal, :as => 'anuncios_t'
  end

  controller :dashboard do
    get 'Mi_Panel' => :index, :as => 'dashboard_index' 
    get 'Mi_Panel/Administracion_de_Cuenta' =>:login, :as => 'dashboard_login'
    get 'Mi_Panel/equipos' => :equipos, :as => 'dashboard_equipos'
    get 'Mi_Panel/:equip/galerias' => :gallerias, :as => 'dashboard_gallerias'
    get 'Mi_Panel/:equip/:gal/imagenes' => :imagenes, :as => 'dashboard_imagenes'
    get 'Mi_Panel/:equip/:gal/videos' => :videos, :as => 'dashboard_videos'
    get 'Mi_Panel/Mis_Equipos' => :equip_history, :as => 'dashboard_equip_history'
    get 'Mi_Panel/Reporte_de_Estado' => :report_status, :as => 'dashboard_status_rep'
    get 'Mi_Panel/Mis_Equipos_Favoritos' => :favorites , :as => 'dashboard_favorite'
  end  

  controller :categories do
    get 'category/vista' => :vista
  end
  
  get 'auth/:provider/callback', to: 'sessions#createfb'
  post 'auth/:provider/callback', to: 'sessions#createfb'
  get 'auth/failure', to: redirect('/')
  post 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy'
  post 'signout', to: 'sessions#destroy'

  get 'auth/google_oauth2/callback?error=access_denied', to: redirect('/')
  get 'nosotros', to: 'welcome#nosotros'
  get 'especiales', to: 'welcome#especiales'
  get 'marcas', to: 'welcome#marcas'
  get 'contactanos', to: 'welcome#contactanos'      

  

  root 'welcome#index'

end

app/controllers/equipment_rent_controller.rb
#!/bin/env ruby
# encoding: utf-8
class EquipmentRentController < ApplicationController
before_action :set_equipment, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  skip_before_action :authorize, only: [:show,:grid,:search,:industry]

  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.where_activo.where_renta
  end

  # GET /equipment/1
  # GET /equipment/1.json
	def show
	    @categoria = Category.find(@equipment.category_id)
	    if @categoria.father_id != 0
	      categoria2 = Category.find(@categoria.father_id)
	      add_breadcrumb categoria2.slug.to_s, Filtro_path('categoria' => categoria2.title, 'tipo' => 1)
	    end 
	    add_breadcrumb @categoria.slug.to_s, Filtro_path('categoria' => @categoria.title, 'tipo' => 1)
	    add_breadcrumb @equipment.slug.to_s, equipment_path(@equipment)   
	    if @equipment.image_id
	      @image = Image.find(@equipment.image_id)
	    else
	      @image = Image.find_by(image_url: '/data/dummy.png')  
	    end  
	     @gallery = Gallery.where('equipment_id = ?', @equipment.id)
	     @user = User.find(@equipment.user_id)
	     @currency = Currency.find(@equipment.currency_id)
	     @comments = Comment.where('equipment_id = ?', @equipment.id)
	     
	     # puts "-------------------Comments---------------------------"
	     # puts @comments.inspect
	     # puts "----------------------------------------------"    

	     @comment = Comment.new('user_id' => session[:user_id],"equipment_id" => @equipment.id)
	end

  # GET /equipment/new
  def new
    add_breadcrumb 'newequipment', new_equipment_path
    @equipment = Equipment.new('user_id' => session[:user_id])
  end

  # GET /equipment/1/edit
  def edit
    if propiedad(@equipment.user_id)
      add_breadcrumb @equipment.name.to_s, edit_equipment_path(@equipment)
    else
      redirect_to equipment_path(@equipment), notice: 'no esta autorizado a hacer cambios en ese equipo'
    end  
  end

  # POST /equipment
  # POST /equipment.json
	def create
	    #@equipment = Equipment.new(equipment_params)
	    session[:url_to_return] = ""
	    @user = User.find(session[:user_id])
	    @equipment = Equipment.new(equipment_params)
	    # puts "-------------------Equipo---------------------------"
	    #   puts @equipment.inspect
	    # puts "----------------------------------------------"
	    #   @pic = params[:equipment][:image_id]
	    # puts "-------------------Pic---------------------------"
	    #   puts @pic.inspect
	    # puts "----------------------------------------------"
	    # puts "-------------------Pics---------------------------"
	    #   puts @pics.inspect
	    # puts "--------------------------------------------------" 
	    respond_to do |format|
	      if secure_save(@equipment)
	        format.html { 
	          #saco la id del proyecto
	          @equipments = Equipment.find(@equipment)
	          # puts "-------------------Equipo---------------------------"
	          # puts @equipments.inspect
	          # puts "------------------------------------------------------"
	          ########################
	          unless @pic.nil?
	            @pics = DataFile.save(@pic,@equipments.id.to_s, @equipments.slug.to_s)
	          else
	            @pics = "/data/dummy.png"  
	          end
	          ########################
	          
	          
	          #creo la galleria
	            @gallery=Gallery.new("equipment_id"=>@equipments.id, "title" =>"principal")
	            # puts "--------------------Galleria--------------------------"
	            # puts @gallery.inspect
	            # puts "------------------------------------------------------"
	            respond_to do |format|
	              if secure_save(@gallery)
	                format.html {
	                  @galleries = Gallery.find(@gallery)
	                    unless @pic.nil?
	                    #puts "pase la validacion de pic"
	                      @image = Image.new("gallery_id" => @galleries.id, "image_url" => @pics)
	                      #puts "--------------------Imagen--------------------------"
	                      #puts @image.inspect
	                      #puts "----------------------------------------------------"
	                      
	                      respond_to do |format|
	                        if secure_save(@image)
	                       #   puts "entre a imagen"
	                          format.html { 
	                            respond_to do |format|
	                              if @equipments.update("image_id" => @image.id)
	                                format.html { 
	                                 #me voy al show del equipo
	                                  Mailer.create_equip(@user,@equipment).deliver
	                                  redirect_to @equipment, notice: 'Equipment was successfully created.'
	                                }
	                                format.json { }
	                              else
	                                format.html { redirect_to root_path, alert: "fallo el update de proyecto" }
	                                format.json {  }
	                              end
	                            end                      
	                          }
	                          format.json { }
	                        else
	                        #  puts "entre a imagen"
	                          format.html { redirect_to root_path, alert: "fallo el salvado de la imagen" }
	                          format.json {  }
	                        end
	                      end
	                    else
	                      redirect_to @equipment, notice: 'Equipment was successfully created.'
	                    end  
	                }
	                format.json {  }
	              else
	                format.html { redirect_to root_path, alert: "fallo el salvado de la Galeria" }
	                format.json {  }
	              end
	            end
	              
	        }
	        format.json { render :show, status: :created, location: @equipment }
	      else
	        format.html { render :new }
	        format.json { render json: @equipment.errors, status: :unprocessable_entity }
	      end
	    end
=begin
	    respond_to do |format|
	      if @equipment.save
	        format.html { redirect_to @equipment, notice: 'Equipment was successfully created.' }
	        format.json { render :show, status: :created, location: @equipment }
	      else
	        format.html { render :new }
	        format.json { render json: @equipment.errors, status: :unprocessable_entity }
	      end
	    end
=end    
	end

  # PATCH/PUT /equipment/1
  # PATCH/PUT /equipment/1.json
	def update

	    if propiedad(@equipment.user_id)
	      @pic = params[:equipment][:image_id]
	      # puts "-------------------Pic---------------------------"
	      #   puts @pic.inspect
	      # puts "----------------------------------------------"
	      # puts "-------------------Pics---------------------------"
	      #   puts @pics.inspect
	      # puts "--------------------------------------------------" 

	      respond_to do |format|
	        if @equipment.update(equipment_params)
	          format.html { 
	            unless @pic.nil?
	              @pics = DataFile.save(@pic,@equipment.id.to_s, @equipment.slug.to_s)
	            else
	              @pics = nil
	            end
	            unless @pics.nil?
	            #creo la galleria
	              @gal = Gallery.where("equipment_id = ? and title = 'principal' ", @equipment.id ).count
	              if @gal > 0 
	  #                puts "--------------------------gal count---------------------------------"
	  #               puts "-----" + @gal.to_s + "----------------------------------------------"
	  #              puts "--------------------------------------------------------------------"
	                @gallery=Gallery.where("equipment_id = ? and title = 'principal' ", @equipment.id ).first
	              else
	                @gallery=Gallery.new("equipment_id"=>@equipment.id, "title" =>"principal")
	              end    
	   #             puts "--------------------Galleria--------------------------"
	    #            puts @gallery.inspect
	     #           puts "------------------------------------------------------"
	                respond_to do |format|
	                  if secure_save(@gallery)
	                    format.html {
	                      @galleries = Gallery.find(@gallery)
	                      
	      #                  puts "pase la validacion de pic"
	                          @image = Image.new("gallery_id" => @galleries.id, "image_url" => @pics)
	                          puts "--------------------Imagen--------------------------"
	                          puts @image.inspect
	                          puts "----------------------------------------------------"
	                          
	                          respond_to do |format|
	                            if secure_save(@image)
	       #                       puts "entre a imagen"
	                              format.html { 
	                                respond_to do |format|
	                                  if @equipment.update("image_id" => @image.id)
	                                    format.html { 
	                                     #me voy al show del equipo
	                                      redirect_to dashboard_equipos_path, notice: 'Los cambios se han guardado con exito' 
	                                    }
	                                    format.json { }
	                                  else
	                                    format.html { redirect_to root_path, alert: "fallo el update de proyecto" }
	                                    format.json {  }
	                                  end
	                                end                      
	                              }
	                              format.json { }

app/helpers/equipment_rent_helper.rb
module EquipmentRentHelper
end

app/views/equipment_rent/index.html.erb
<h1>Lista de Anuncios</h1>
<% @equipment.each do |equipment| %>
<div class="lista_show_equipment">
  <% if equipment.image_id %>
    <% @image = Image.find(equipment.image_id) %>
  <div class="lista_image"><img src="<%= @image.image_url %>"></div>
  <% else %>
    <div class="lista_image"><img src="/data/dummy.png"></div>
  <% end %>
  <div class="datos">
    <div class="titulo">
      <%= link_to equipment.name, equipment_path(equipment) %>
    </div>
    <div class="descripcion">
     Marca:<%= equipment.brand_id %> | Modelo: <%= equipment.modelo %> 
     <br>
     Año: <%= equipment.year %> | Color: <%= equipment.color %>
    </div>
  </div>
  <div class="precio">
    Precio <%if equipment.publication_type == 1 %>Venta<% else %>Renta<% end %>: <%= number_to_currency(equipment.precio) %> <%= equipment.currency_id %>
  </div>
  <div class="opciones">
    <%#= link_to 'Edit', edit_equipment_path(equipment) %> 
    <%= link_to 'Imagenes', galeria_index_path(equipment) %> 
    <%#= link_to 'Destroy', equipment, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>    
</div>
<% end %>

app/views/equipment_rent/master_console.html.erb
 <%= form_tag (master_console_exe_path) do %>
	<%= hidden_field_tag 'equip', @equipment%>
	<%= label_tag 'rank', 'Rango:' %></br>
	<%= select_tag 'rank', options_for_select([ "1", "2", "3", "4" , "5" , "6" ], @equipment.rank) %> </br>
	<%= label_tag 'priority', 'Prioridad:' %></br>
	<%= select_tag 'priority', options_for_select([ "1", "2", "3", "4" , "5" , "6" ], @equipment.priority) %></br>

	<%= submit_tag "Edit this article" %>
<%end%>

app/views/equipment_rent/new.html.erb
<h1>Crea tu Anuncio</h1>

<%#= render 'form' %>
<script type='text/javascript'>
           
function validateFiles(inputFile) {
var maxExceededMessage = "El Archivo excede el limite pérmitido (1 MB)";
var extErrorMessage = "Solo se aceptan extenciones: .jpg, .jpeg, .gif or .png ";
var allowedExtension = ["jpg", "jpeg", "gif", "png"];
             
var extName;
var maxFileSize = $(inputFile).data('max-file-size');
var sizeExceeded = false;
var extError = false;
             
$.each(inputFile.files, function() {
  if (this.size && maxFileSize && this.size > parseInt(maxFileSize)) {sizeExceeded=true;};
    extName = this.name.split('.').pop();
  if ($.inArray(extName, allowedExtension) == -1) {extError=true;};});
    if (sizeExceeded) {
      window.alert(maxExceededMessage);
        $(inputFile).val('');
          };
    if (extError) {
      window.alert(extErrorMessage);
        $(inputFile).val('');
          };
}

</script>
<!-- aqui-->
<div class="alta_equipment">

  <%= form_for(@equipment) do |f| %>
    <% if @equipment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@equipment.errors.count, "error") %> No permiten que su solicitud sea procesada:</h2>

        <ul>
        <% @equipment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <h1>Servicios</h1>
  <div class="grupo">
      <div class="grupo_1">
        <%= f.label :publication_type %><br>
        <%= select("equipment","publication_type", options_for_select([['Compra',1],['Renta',2]])) %><br>
      </div> 
      <div class="grupo_1">
        <%= f.label :precio, "Precio de Venta" %><br>
        <%= f.number_field :precio, required: true %><br><br>
        <%= f.label :currency_id, "Tipo de Moneda"  %><br>
        <%= select("equipment", "currency_id", Currency.all.collect {|p| [ p.name, p.id ] }.uniq, required: true) %><br><br>
      </div> 
  </div>

  <h1>Categoria</h1>
  <div class="grupo">
      <%#= select("equipment", "category_id", Category.where('father_id = 0').collect {|p| [ p.title, p.id ] }.uniq, required: true) %>
      

        <%= f.collection_select :category_id, Category.order(:id), :id, :title , include_blank: true, required: true  %><br>        
        <%= f.grouped_collection_select :subcategory_id, Category.order(:id), :subcategories, :title, :id, :title, include_blank: true , required: true%><br>
      <%#= option_groups_from_collection_for_select(@categorias_p, :id, :title, :father_id, :title) %>
      <%#= grouped_options_for_select(categorias_p)%>
  </div>

  <h1>Selecciona tu paquete</h1>
  <div class="grupo"> 
      <%= select("equipment", "package_id", Package.all.collect {|p| [ p.name, p.id ] }.uniq, required: true) %>
  </div>

  <h1>Descripción</h1>
  <div class="grupo">
      <%= f.label :image_id, "Seleccione una imagen" %> 
      <%= f.file_field :image_id ,:onchange =>"validateFiles(this);",:data => {:max_file_size => 1.megabytes} %><br><br>
      <%= f.label :name, "Titulo del anuncio" %><br>
      <%= f.text_field :name, required: true %><br><br>
      <%= f.label :name, "Escribe las palabras claves separadas por una coma con las que quieras que sea identifique tu producto:" %><br>
      <%= f.text_field :etiquetas %><br><br>      
      <%= f.label :description, "Descripción" %><br>
      <%= f.text_area :description, cols: "90", rows: "10" %><br>    
  </div>

  <h1>Detalles</h1>
  <div class="grupo">
      <div class="grupo_1">      
        <%= f.label :brand_id %><br>
        <%= select("equipment", "brand_id", Brand.all.collect {|p| [ p.name, p.id ] }.uniq, required: true) %><br>    
        <%= f.label :modelo %><br>
        <%= f.text_field :modelo, required: true  %><br> 
        <%= f.label :year %><br>
        <%= f.number_field :year, maxlength: "4" , in: 1950...2030%><br>
        <%= f.label :color %><br>
        <%= f.text_field :color %><br>
      </div>
      <div class="grupo_1">                    
        <%= f.label :country_id %><br>
        <%= f.collection_select :country_id, Country.order(:id), :id, :name , include_blank: true, required: true  %><br>   
        <%= f.label :state_id %><br>
        <%= f.grouped_collection_select :state_id, Country.order(:id), :states, :name, :id, :name, include_blank: true , required: true%><br>      
        <%= f.label :ciudad %><br>
        <%= f.text_field :ciudad, required: true  %><br>
      </div>               
  </div>

  <div class="field">
    <%#= f.label :user_id %><br>
    <%= f.hidden_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit "Crear Anuncio" %>
  </div>
</div>    

<% end %>


<%#= link_to 'Back', equipment_index_path %>

app/views/equipment_rent/search.html.erb
<% form_tag search_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table id ="equipments" class ="pretty" >
		<thead>
			<tr>
				<td align="center"> <%= sortable "Nombre" %></td>
				<td align="center"> <%= sortable "Año" %></td>
				<td align="center"> <%= sortable "Color" %></td>
				<td align="center"> <%= sortable "Marca" %></td>
				<td align="center"> <%= sortable "Paquete" %></td>
				<td align="center"> <%= sortable "Precio" %></td>
				<td align="center"> <%= sortable "Modelo" %></td>
				<td align="center"> <%= sortable "Moneda" %></td>
				<td align="center"> <%= sortable "Pais" %></td>
				<td align="center"> <%= sortable "Estado" %></td>
				<td align="center"> <%= sortable "Ciudad" %></td>
				<td align="center"> <%= sortable "Categoria" %></td>
			</tr>
		</thead>
		

		<tbody>	
		<% unless @equipments.nil? %>		
		    <% @equipments.each do |equipment| %>
		      <tr>
		        <td align="center"><%= link_to equipment.name, equipment_path(equipment) %></td>
		        <td align="center"><%= equipment.year %></td>
		        <td align="center"><%= equipment.color %></td>
		        <td align="center"><%= equipment.brand.name %></td>
		        <td align="center"><%= equipment.package.name %></td>
		        <td align="center"><%= number_to_currency(equipment.precio) %></td>
		        <td align="center"><%= equipment.modelo %></td>
		        <td align="center"><%= equipment.currency.name %></td>
		        <td align="center"><%= equipment.country.name %></td>
		        <td align="center"><%= equipment.state.name %></td>
		        <td align="center"><%= equipment.ciudad %></td>
		        <td align="center"><%= equipment.category.title %></td>
		      </tr>
		    <% end %>
		<% else %>
			<tr> <td> No hay resultados a su busqueda</td> </tr>	    
		<% end %>    

	  	</tbody>
    </table>

app/views/equipment_rent/show.html.erb
<p id="notice"><%= notice %></p>

<!--      REDES SOCIALES          -->

<%= render 'layouts/social_section', :title => "I wanna share this", :url => request.original_url %>  

<!--      Vista del equipo          -->
<div class="show_equipment">
  <!--      titulo del equipo          -->
  <div class="titulo"><h2><%= @equipment.name %></h2> 

  <% if User.find_by(id: session[:user_id]) %>
    <%=link_to "favoritos",new_fav_path(:equip => @equipment.id),remote: true %>
  <% end %>  

  </div>
  <!--      imagenes y detalles del equipo          -->
  <div class="producto">
    <div class="preview">
      <div>
      <%
        @gallery.each do |g|
        @images = Image.where('gallery_id' => g.id)
        link_to g.title, 'equipment/galleries/'+ g.equipment_id.to_s
        %>
          <% unless @images.blank?
           @images.each do |img| %>
            <div class="imagenprevia"><img src="<%= img.image_url %>"></div>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div>
      <%
        @video2 = nil
        @gallery.each do |g|
        @video = Video.where('gallery_id' => g.id)
        if @video2 == nil
          @video2 = Video.where('gallery_id' => g.id).first
        end
        link_to g.title, 'equipment/galleries/'+ g.equipment_id.to_s
        %>
          <% unless @video.blank?
           @video.each do |v| %>
            <div class="imagenprevia"><%= v.video_url.html_safe %></div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

      <!--      imagenes principal del equipo          -->
      
      <% if @video2 != nil %>
        <div class="imagen"><%= @video2.video_url.html_safe %></div>
      <%else %>
        <% unless @images.blank? %>
          <% if @image.image_url %>
              <div class="imagen"><img src="<%= @image.image_url %>"></div>
          <%else %>
              <div class="imagen"><img src="/data/dummy.png"></div>  
          <% end %>  
        <% else %>
          <div class="imagen"><img src="/data/dummy.png"></div>    
        <% end %>      
      <% end %>

    <!--      tabla de detalles          -->
    <div class="modelo">
      <table>
        <tr><th colspan="2">Modelo: <%= @equipment.modelo %></th></tr>
        <tr><td>Año: <%= @equipment.year %></td><td>Color: <%= @equipment.color %></td></tr>
        <tr><td>Marca: <%= @equipment.brand.name %></td><td> </td></tr>
        <tr><th colspan="2"><%if @equipment.publication_type == 1 %>Venta<% else %>Renta<% end %>:</th></tr>
        <tr>
          <td colspan="2">Precio: <%= number_to_currency(@equipment.precio) %> <%= @currency.name %></td>
        </tr>
        <tr><th colspan="2">Contacto y localidad</th></tr> 
        <tr>
          <td colspan="2">Lugar: <%= @equipment.ciudad %>, <%= @equipment.state.name %>, <%= @equipment.country.name %></td>
        </tr>
        <tr>
          <td><%= button_to "contacto", equipo_contacto_path(:user_id => session[:user_id], :equipment => @equipment), :method => :post %></td>
          <td><img src="/images/iconos/usuario_icono.png" height="12" width="12"> <%= link_to @user.username, users_view_path(:user_id => @equipment.user_id) %></td>
        </tr>            
      </table>
      </div> 
    </div>
  
  <!--      etiquetas          -->  
  <p>Etiquetas: <%= @equipment.etiquetas %></p>

  <!--      descripcion del equipo          -->
  <div class="descripcion">
    <h1>Description:</h1>
    <textarea readonly><%= @equipment.description %></textarea>
  </div>

  <!--      comentarios          -->
  <h1>Comentarios:</h1>
    <%= render partial: '/comments/form', locals: {equipment: @equipment.slug, comment: @comment} %> 
    <%= render partial: '/comments/index', locals: {equipment: @equipment.slug, comments: @comments} %>
</div>

<%#= link_to 'Edit', edit_equipment_path(@equipment) %>
<%#= link_to 'Back', dashboard_equipos_path %>